#pragma once
#include <stdint.h>

constexpr uint16_t MLX_NATIVE_FEATURE_COUNT = 2;
constexpr uint16_t MLX_NATIVE_IF_TREE_COUNT = 300;
constexpr uint32_t MLX_NATIVE_IF_NODE_COUNT = 40720;
constexpr uint16_t MLX_NATIVE_IF_MAX_SAMPLES = 256;
constexpr uint16_t MLX_NATIVE_OCSVM_SUPPORT_VECTOR_COUNT = 68;

extern const float MLX_NATIVE_IMPUTER_MEDIAN[MLX_NATIVE_FEATURE_COUNT];
extern const float MLX_NATIVE_SCALER_CENTER[MLX_NATIVE_FEATURE_COUNT];
extern const float MLX_NATIVE_SCALER_SCALE[MLX_NATIVE_FEATURE_COUNT];

extern const uint32_t MLX_NATIVE_IF_TREE_OFFSETS[MLX_NATIVE_IF_TREE_COUNT + 1];
extern const int16_t MLX_NATIVE_IF_CHILDREN_LEFT[MLX_NATIVE_IF_NODE_COUNT];
extern const int16_t MLX_NATIVE_IF_CHILDREN_RIGHT[MLX_NATIVE_IF_NODE_COUNT];
extern const int8_t MLX_NATIVE_IF_FEATURE[MLX_NATIVE_IF_NODE_COUNT];
extern const float MLX_NATIVE_IF_THRESHOLD[MLX_NATIVE_IF_NODE_COUNT];
extern const uint16_t MLX_NATIVE_IF_N_NODE_SAMPLES[MLX_NATIVE_IF_NODE_COUNT];
extern const float MLX_NATIVE_IF_OFFSET;

extern const float MLX_NATIVE_OCSVM_SUPPORT_VECTORS[
    MLX_NATIVE_OCSVM_SUPPORT_VECTOR_COUNT * MLX_NATIVE_FEATURE_COUNT
];
extern const float MLX_NATIVE_OCSVM_DUAL_COEF[MLX_NATIVE_OCSVM_SUPPORT_VECTOR_COUNT];
extern const float MLX_NATIVE_OCSVM_INTERCEPT;
extern const float MLX_NATIVE_OCSVM_GAMMA;
